# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 393)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.f_original_img = QtWidgets.QFrame(self.centralwidget)
        self.f_original_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_original_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_original_img.setObjectName("f_original_img")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f_original_img)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_original_img = QtWidgets.QLabel(self.f_original_img)
        self.l_original_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.l_original_img.setObjectName("l_original_img")
        self.verticalLayout.addWidget(self.l_original_img)
        self.original_img = QtWidgets.QLabel(self.f_original_img)
        self.original_img.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(0, 85, 255); \n"
"    border-radius: 5px;      \n"
"}")
        self.original_img.setText("")
        self.original_img.setObjectName("original_img")
        self.original_img.setScaledContents(True)
        self.original_img.setFixedSize(400, 400)

        self.verticalLayout.addWidget(self.original_img)
        self.horizontalLayout.addWidget(self.f_original_img)
        self.f_uploaded_img = QtWidgets.QFrame(self.centralwidget)
        self.f_uploaded_img.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_uploaded_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_uploaded_img.setObjectName("f_uploaded_img")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.f_uploaded_img)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_uploaded_img = QtWidgets.QLabel(self.f_uploaded_img)
        self.l_uploaded_img.setMaximumSize(QtCore.QSize(16777215, 20))
        self.l_uploaded_img.setObjectName("l_uploaded_img")
        self.verticalLayout_2.addWidget(self.l_uploaded_img)
        self.uploaded_img = QtWidgets.QLabel(self.f_uploaded_img)
        self.uploaded_img.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(0, 85, 255); \n"
"    border-radius: 5px;      \n"
"}")
        self.uploaded_img.setText("")
        self.uploaded_img.setObjectName("uploaded_img")
        self.uploaded_img.setScaledContents(True)
        self.uploaded_img.setFixedSize(400, 400)

        self.verticalLayout_2.addWidget(self.uploaded_img)
        self.horizontalLayout.addWidget(self.f_uploaded_img)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.l_message = QtWidgets.QLabel(self.frame_3)
        self.l_message.setMinimumSize(QtCore.QSize(100, 0))
        self.l_message.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(40)
        font.setItalic(False)
        self.l_message.setFont(font)
        self.l_message.setText("")
        self.l_message.setObjectName("l_message")
        self.verticalLayout_3.addWidget(self.l_message, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.pb_load = QtWidgets.QPushButton(self.frame_3)
        self.pb_load.setMinimumSize(QtCore.QSize(100, 0))
        self.pb_load.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pb_load.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.pb_load.setObjectName("pb_load")
        self.verticalLayout_3.addWidget(self.pb_load)
        self.pb_check = QtWidgets.QPushButton(self.frame_3)
        self.pb_check.setMinimumSize(QtCore.QSize(100, 0))
        self.pb_check.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pb_check.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.pb_check.setObjectName("pb_check")
        self.verticalLayout_3.addWidget(self.pb_check)
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l_original_img.setText(_translate("MainWindow", "Original Image"))
        self.l_uploaded_img.setText(_translate("MainWindow", "Uploaded Image"))
        self.pb_load.setText(_translate("MainWindow", "Load Image"))
        self.pb_check.setText(_translate("MainWindow", "Check"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
