# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 633)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_text2text = QtWidgets.QWidget()
        self.tab_text2text.setObjectName("tab_text2text")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_text2text)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.tab_text2text)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 498, 416))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.t1_output_txt = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.t1_output_txt.setStyleSheet("background-color: rgb(0, 85, 255,10);")
        self.t1_output_txt.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.t1_output_txt.setWordWrap(True)
        self.t1_output_txt.setObjectName("t1_output_txt")
        self.verticalLayout_6.addWidget(self.t1_output_txt)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.tab_text2text)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.t1_input_txt = QtWidgets.QLineEdit(self.frame)
        self.t1_input_txt.setMaximumSize(QtCore.QSize(16777215, 50))
        self.t1_input_txt.setObjectName("t1_input_txt")
        self.horizontalLayout_2.addWidget(self.t1_input_txt)
        self.t1_pb_send = QtWidgets.QPushButton(self.frame)
        self.t1_pb_send.setMinimumSize(QtCore.QSize(100, 0))
        self.t1_pb_send.setMaximumSize(QtCore.QSize(100, 16777215))
        self.t1_pb_send.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    margin: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.t1_pb_send.setObjectName("t1_pb_send")
        self.horizontalLayout_2.addWidget(self.t1_pb_send)
        self.verticalLayout.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_text2text, "")
        self.tab_textAndImage2text = QtWidgets.QWidget()
        self.tab_textAndImage2text.setObjectName("tab_textAndImage2text")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_textAndImage2text)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.tab_textAndImage2text)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.l_uploaded_img_tab = QtWidgets.QLabel(self.frame_3)
        self.l_uploaded_img_tab.setMaximumSize(QtCore.QSize(16777215, 20))
        self.l_uploaded_img_tab.setObjectName("l_uploaded_img_tab")
        self.verticalLayout_2.addWidget(self.l_uploaded_img_tab)
        self.t2_uploaded_img = QtWidgets.QLabel(self.frame_3)
        self.t2_uploaded_img.setMinimumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(31)
        self.t2_uploaded_img.setFont(font)
        self.t2_uploaded_img.setStyleSheet("QLabel {\n"
"    border: 1px solid rgb(0, 85, 255); \n"
"    border-radius: 5px;      \n"
"}")
        self.t2_uploaded_img.setScaledContents(True)
        self.t2_uploaded_img.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_uploaded_img.setObjectName("t2_uploaded_img")
        self.verticalLayout_2.addWidget(self.t2_uploaded_img)
        self.t2_scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.t2_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.t2_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.t2_scrollArea.setWidgetResizable(True)
        self.t2_scrollArea.setObjectName("t2_scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 498, 86))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.t2_output_txt = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.t2_output_txt.setStyleSheet("background-color: rgb(0, 85, 255,10);")
        self.t2_output_txt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.t2_output_txt.setText("")
        self.t2_output_txt.setWordWrap(True)
        self.t2_output_txt.setObjectName("t2_output_txt")
        self.verticalLayout_5.addWidget(self.t2_output_txt)
        self.t2_scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.t2_scrollArea)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.tab_textAndImage2text)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.t2_input_txt = QtWidgets.QLineEdit(self.frame_4)
        self.t2_input_txt.setMaximumSize(QtCore.QSize(16777215, 50))
        self.t2_input_txt.setObjectName("t2_input_txt")
        self.horizontalLayout_3.addWidget(self.t2_input_txt)
        self.t2_pb_upload = QtWidgets.QPushButton(self.frame_4)
        self.t2_pb_upload.setMinimumSize(QtCore.QSize(100, 0))
        self.t2_pb_upload.setMaximumSize(QtCore.QSize(100, 16777215))
        self.t2_pb_upload.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    margin: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.t2_pb_upload.setObjectName("t2_pb_upload")
        self.horizontalLayout_3.addWidget(self.t2_pb_upload)
        self.t2_pb_send = QtWidgets.QPushButton(self.frame_4)
        self.t2_pb_send.setMinimumSize(QtCore.QSize(100, 0))
        self.t2_pb_send.setMaximumSize(QtCore.QSize(100, 16777215))
        self.t2_pb_send.setStyleSheet("QPushButton {\n"
"    padding: 5px;\n"
"    margin: 5px;\n"
"    border-radius: 5px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: rgb(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgb(0, 85, 255, 200);\n"
"}\n"
"\n"
"")
        self.t2_pb_send.setObjectName("t2_pb_send")
        self.horizontalLayout_3.addWidget(self.t2_pb_send)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.tabWidget.addTab(self.tab_textAndImage2text, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.t1_output_txt.setText(_translate("MainWindow", "--Chat History--"))
        self.t1_input_txt.setPlaceholderText(_translate("MainWindow", "Input your prompt!"))
        self.t1_pb_send.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_text2text), _translate("MainWindow", "Prompt → Text"))
        self.l_uploaded_img_tab.setText(_translate("MainWindow", "Uploaded Image"))
        self.t2_uploaded_img.setText(_translate("MainWindow", "🖼️"))
        self.t2_input_txt.setPlaceholderText(_translate("MainWindow", "Input your prompt!"))
        self.t2_pb_upload.setText(_translate("MainWindow", "Upload"))
        self.t2_pb_send.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_textAndImage2text), _translate("MainWindow", "Prompt + Image → Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
